
RGraph=window.RGraph||{isrgraph:true,isRGraph:true,rgraph:true};RGraph.Pie=function(conf)
{var id=conf.id,canvas=document.getElementById(id),data=conf.data;this.id=id;this.canvas=canvas;this.context=this.canvas.getContext?this.canvas.getContext("2d",{alpha:(typeof id==='object'&&id.alpha===false)?false:true}):null;this.canvas.__object__=this;this.total=0;this.subTotal=0;this.angles=[];this.data=data;this.properties=[];this.type='pie';this.isRGraph=true;this.isrgraph=true;this.rgraph=true;this.coords=[];this.coords.key=[];this.coordsSticks=[];this.coordsText=[];this.uid=RGraph.createUID();this.canvas.uid=this.canvas.uid?this.canvas.uid:RGraph.createUID();this.colorsParsed=false;this.original_colors=[];this.firstDraw=true;this.exploding=null;for(var i=0;i<this.data.length;++i){if(typeof this.data[i]==='string'){this.data[i]=parseFloat(this.data[i]);}}
this.properties={centerxAdjust:0,centeryAdjust:0,colors:['red','#ccc','#cfc','blue','pink','yellow','black','orange','cyan','purple','#78CAEA','#E284E9','white','blue','#9E7BF6'],colorsStroke:'white',linewidth:3,labels:[],labelsFont:null,labelsSize:null,labelsColor:null,labelsBold:null,labelsItalic:null,labelsSticks:false,labelsSticksLength:7,labelsSticksColors:null,labelsSticksLinewidth:1,labelsSticksHlength:5,labelsList:true,labelsIngraph:null,labelsIngraphColor:null,labelsIngraphFont:null,labelsIngraphSize:null,labelsIngraphBold:null,labelsIngraphItalic:null,labelsIngraphBounding:true,labelsIngraphBoundingFill:'rgba(255,255,255,0.85)',labelsIngraphBoundingStroke:'rgba(0,0,0,0)',labelsIngraphSpecific:null,labelsIngraphUnitsPre:'',labelsIngraphUnitsPost:'',labelsIngraphPoint:'.',labelsIngraphThousand:',',labelsIngraphDecimals:0,labelsIngraphRadius:null,labelsCenter:null,labelsCenterSize:26,labelsCenterFont:null,labelsCenterColor:null,labelsCenterItalic:null,labelsCenterBold:null,marginLeft:25,marginRight:25,marginTop:25,marginBottom:25,title:'',titleBackground:null,titleHpos:null,titleVpos:0.5,titleBold:null,titleFont:null,titleSize:null,titleColor:null,titleItalic:null,titleX:null,titleY:null,titleHalign:null,titleValign:null,shadow:true,shadowColor:'#aaa',shadowOffsetx:0,shadowOffsety:0,shadowBlur:15,textBold:false,textItalic:false,textSize:12,textColor:'black',textFont:'Arial, Verdana, sans-serif',textAccessible:true,textAccessibleOverflow:'visible',textAccessiblePointerevents:false,contextmenu:null,tooltips:null,tooltipsEvent:'onclick',tooltipsEffect:'fade',tooltipsCssClass:'RGraph_tooltip',tooltipsHighlight:true,highlightStyle:'2d',highlightStyleTwodFill:'rgba(255,255,255,0.7)',highlightStyleTwodStroke:'rgba(255,255,255,0.7)',highlightStyleOutlineWidth:null,centerx:null,centery:null,radius:null,border:false,borderColor:'rgba(255,255,255,0.5)',key:null,keyBackground:'white',keyPosition:'graph',keyHalign:'right',keyShadow:false,keyShadowColor:'#666',keyShadowBlur:3,keyShadowOffsetx:2,keyShadowOffsety:2,keyPositionGutterBoxed:false,keyPositionX:null,keyPositionY:null,keyColorShape:'square',keyRounded:true,keyLinewidth:1,keyColors:null,keyInteractive:false,keyInteractiveHighlightChartStroke:'black',keyInteractiveHighlightChartFill:'rgba(255,255,255,0.7)',keyInteractiveHighlightLabel:'rgba(255,0,0,0.2)',keyLabelsColor:null,keyLabelsFont:null,keyLabelsSize:null,keyLabelsBold:null,keyLabelsItalic:null,keyLabelsOffsetx:0,keyLabelsOffsety:0,annotatable:false,annotatableColor:'black',resizable:false,resizableHandleAdjust:[0,0],resizableHandleBackground:null,variant:'pie',variantDonutWidth:null,variantThreedDepth:20,exploded:[],effectRoundrobinMultiplier:1,centerpin:null,centerpinFill:'gray',centerpinStroke:'white',origin:0-(Math.PI/2),clearto:'rgba(0,0,0,0)',events:true,images:null}
for(var i=0,len=data.length;i<len;i++){this.total+=data[i];this['$'+i]={};}
if(!this.canvas.__rgraph_aa_translated__){this.context.translate(0.5,0.5);this.canvas.__rgraph_aa_translated__=true;}
var prop=this.properties;this.path=RGraph.pathObjectFunction;if(RGraph.Effects&&typeof RGraph.Effects.decorate==='function'){RGraph.Effects.decorate(this);}
this.responsive=RGraph.responsive;this.set=function(name)
{var value=typeof arguments[1]==='undefined'?null:arguments[1];if(arguments.length===1&&typeof arguments[0]==='object'){for(i in arguments[0]){if(typeof i==='string'){this.set(i,arguments[0][i]);}}
return this;}
prop[name]=value;return this;};this.get=function(name)
{return prop[name];};this.draw=function()
{RGraph.fireCustomEvent(this,'onbeforedraw');this.marginLeft=prop.marginLeft;this.marginRight=prop.marginRight;this.marginTop=prop.marginTop;this.marginBottom=prop.marginBottom;this.radius=this.getRadius();this.centerx=(this.graph.width/2)+this.marginLeft+prop.centerxAdjust;this.centery=(this.graph.height/2)+this.marginTop+prop.centeryAdjust;this.subTotal=prop.origin;this.angles=[];this.coordsText=[];if(typeof prop.radius==='number')this.radius=prop.radius;if(typeof prop.centerx==='number')this.centerx=prop.centerx;if(typeof prop.centery==='number')this.centery=prop.centery;if(this.radius<=0){return;}
if(!this.colorsParsed){this.parseColors();this.colorsParsed=true;}
if(prop.variant.indexOf('3d')>0){return this.draw3d();}
RGraph.drawTitle(this,prop.title,(this.canvas.height/2)-this.radius-5,this.centerx,prop.titleSize?prop.titleSize:prop.textSize);this.total=RGraph.arraySum(this.data);var tot=this.total;var data=this.data;for(var i=0,len=this.data.length;i<len;i++){var angle=((data[i]/tot)*RGraph.TWOPI);this.drawSegment(angle,prop.colors[i],i==(len-1),i);}
RGraph.noShadow(this);if(prop.linewidth>0){this.drawBorders();}
var len=this.angles.length;var r=this.radius;for(var action=0;action<2;action+=1){for(var i=0;i<len;i++){this.context.beginPath();var segment=this.angles[i];if(action===1){this.context.strokeStyle=typeof(prop.colorsStroke)=='object'?prop.colorsStroke[i]:prop.colorsStroke;}
prop.colors[i]?this.context.fillStyle=prop.colors[i]:null;this.context.lineJoin='round';this.context.arc(segment[2],segment[3],r,(segment[0]),(segment[1]),false);if(prop.variant=='donut'){this.context.arc(segment[2],segment[3],typeof(prop.variantDonutWidth)=='number'?r-prop.variantDonutWidth:r/2,(segment[1]),(segment[0]),true);}else{this.context.lineTo(segment[2],segment[3]);}
this.context.closePath();action===0?this.context.fill():this.context.stroke();}}
if(prop.labelsSticks){this.drawSticks();var strokeStyle=prop.colorsStroke;}
if(prop.labels){this.drawLabels();}
if(prop.centerpin){this.drawCenterpin();}
if(prop.labelsIngraph){this.drawInGraphLabels();}
if(typeof prop.labelsCenter==='string'){this.drawCenterLabel(prop.labelsCenter);}
if(prop.contextmenu){RGraph.showContext(this);}
if(prop.border){this.context.beginPath();this.context.lineWidth=5;this.context.strokeStyle=prop.borderColor;this.context.arc(this.centerx,this.centery,this.radius-2,0,RGraph.TWOPI,0);this.context.stroke();}
if(prop.key&&prop.key.length){RGraph.drawKey(this,prop.key,prop.colors);}
RGraph.noShadow(this);if(prop.resizable){RGraph.allowResizing(this);}
if(prop.events==true){RGraph.installEventListeners(this);}
if(this.firstDraw){this.firstDraw=false;RGraph.fireCustomEvent(this,'onfirstdraw');this.firstDrawFunc();}
RGraph.fireCustomEvent(this,'ondraw');return this;};this.exec=function(func)
{func(this);return this;};this.drawSegment=function(radians,color,last,index)
{var subTotal=this.subTotal;radians=radians*prop.effectRoundrobinMultiplier;this.context.beginPath();color?this.context.fillStyle=color:null;this.context.strokeStyle=prop.colorsStroke;this.context.lineWidth=0;if(prop.shadow){RGraph.setShadow(this,prop.shadowColor,prop.shadowOffsetx,prop.shadowOffsety,prop.shadowBlur);}
if((typeof(prop.exploded)=='object'&&prop.exploded[index]>0)||typeof(prop.exploded)=='number'){var explosion=typeof(prop.exploded)=='number'?prop.exploded:prop.exploded[index];var x=0;var y=0;var h=explosion;var t=subTotal+(radians/2);var x=(Math.cos(t)*explosion);var y=(Math.sin(t)*explosion);var r=this.radius;this.context.moveTo(this.centerx+x,this.centery+y);}else{var x=0;var y=0;var r=this.radius;}
var startAngle=subTotal;var endAngle=((subTotal+radians));this.context.arc(this.centerx+x,this.centery+y,r,startAngle,endAngle,0);if(prop.variant=='donut'){this.context.arc(this.centerx+x,this.centery+y,typeof(prop.variantDonutWidth)=='number'?r-prop.variantDonutWidth:r/2,endAngle,startAngle,true);}else{this.context.lineTo(this.centerx+x,this.centery+y);}
this.context.closePath();this.angles.push([subTotal,subTotal+radians,this.centerx+x,this.centery+y]);this.context.fill();this.subTotal+=radians;};this.drawLabels=function()
{if(prop.labels.length&&prop.labelsList){return this.drawLabelsList();}
var hAlignment='left',vAlignment='center',labels=prop.labels,context=this.context,font=prop.textFont,bold=prop.labelsBold,text_size=prop.textSize,cx=this.centerx,cy=this.centery,r=this.radius;RGraph.noShadow(this);this.context.fillStyle='black';this.context.beginPath();if(labels&&labels.length){var textConf=RGraph.getTextConf({object:this,prefix:'labels'});for(i=0;i<this.angles.length;++i){var segment=this.angles[i];if(typeof labels[i]!='string'&&typeof labels[i]!='number'){continue;}
this.context.moveTo(cx,cy);var a=segment[0]+((segment[1]-segment[0])/2),angle=((segment[1]-segment[0])/2)+segment[0];if(typeof prop.exploded==='object'&&prop.exploded[i]||typeof prop.exploded=='number'){var t=((segment[1]-segment[0])/2),seperation=typeof(prop.exploded)=='number'?prop.exploded:prop.exploded[i];var explosion_offsetx=(Math.cos(angle)*seperation),explosion_offsety=(Math.sin(angle)*seperation);}else{var explosion_offsetx=0,explosion_offsety=0;}
if(prop.labelsSticks){explosion_offsetx+=(Math.cos(angle)*(typeof prop.labelsSticksLength==='object'?prop.labelsSticksLength[i]:prop.labelsSticksLength));explosion_offsety+=(Math.sin(angle)*(typeof prop.labelsSticksLength==='object'?prop.labelsSticksLength[i]:prop.labelsSticksLength));}
var x=cx+explosion_offsetx+((r+10)*Math.cos(a))+(prop.labelsSticks?(a<RGraph.HALFPI||a>(RGraph.TWOPI+RGraph.HALFPI)?2:-2):0),y=cy+explosion_offsety+(((r+10)*Math.sin(a)));if(this.coordsSticks&&this.coordsSticks[i]){var x=this.coordsSticks[i][4][0]+(x<cx?-5:5),y=this.coordsSticks[i][4][1];}
vAlignment='center';hAlignment=x<cx?'right':'left';this.context.fillStyle=prop.textColor;RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x,y:y,text:labels[i],valign:vAlignment,halign:hAlignment,tag:'labels'});}
this.context.fill();}};this.drawLabelsList=function()
{var segment=this.angles[i],labels=prop.labels,labels_right=[],labels_left=[],left=[],right=[],centerx=this.centerx,centery=this.centery,radius=this.radius,offset=50
for(var i=0;i<this.angles.length;++i){if(RGraph.isNull(this.data[i])){continue;}
var angle=this.angles[i][0]+((this.angles[i][1]-this.angles[i][0])/2),endpoint_inner=RGraph.getRadiusEndPoint(centerx,centery,angle,radius+5),endpoint_outer=RGraph.getRadiusEndPoint(centerx,centery,angle,radius+30),explosion=[(typeof prop.exploded==='number'?prop.exploded:prop.exploded[i]),(Math.cos(angle)*(typeof prop.exploded==='number'?prop.exploded:prop.exploded[i])),(Math.sin(angle)*(typeof prop.exploded==='number'?prop.exploded:prop.exploded[i]))]
var textConf=RGraph.getTextConf({object:this,prefix:'labels'});if(angle>(-1*RGraph.HALFPI)&&angle<RGraph.HALFPI){labels_right.push([i,angle,labels[i]?labels[i]:'',endpoint_inner,endpoint_outer,textConf.color,RGraph.arrayClone(explosion)]);}else{labels_left.push([i,angle,labels[i]?labels[i]:'',endpoint_inner,endpoint_outer,textConf.color,RGraph.arrayClone(explosion)]);}}
var vspace_right=(this.canvas.height-prop.marginTop-prop.marginBottom)/labels_right.length
for(var i=0,y=(prop.marginTop+(vspace_right/2));i<labels_right.length;y+=vspace_right,i++){if(labels_right[i][2]){var x=this.centerx+this.radius+offset,idx=labels_right[i][0],explosionX=labels_right[i][6][0]?labels_right[i][6][1]:0,explosionY=labels_right[i][6][0]?labels_right[i][6][2]:0
var ret=RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x+explosionX,y:y+explosionY,text:labels_right[i][2],valign:'center',halign:'left',tag:'labels',color:labels_right[i][5]});if(ret&&ret.node){ret.node.__index__=labels_right[i][0];}
this.path({path:'lc round lw % b m % % qc % % % % s %',args:[prop.labelsSticksLinewidth,labels_right[i][3][0]+explosionX,labels_right[i][3][1]+explosionY,labels_right[i][4][0]+explosionX,labels_right[i][4][1]+explosionY,ret.x-5,ret.y+(ret.height/2),labels_right[i][5]]});this.path({path:'b a % % 2 0 6.2830 false, f %',args:[ret.x-5,ret.y+(ret.height/2),labels_right[i][5]]});}}
var vspace_left=(this.canvas.height-prop.marginTop-prop.marginBottom)/labels_left.length
for(var i=(labels_left.length-1),y=(prop.marginTop+(vspace_left/2));i>=0;y+=vspace_left,i--){if(labels_left[i][2]){var x=this.centerx-this.radius-offset,idx=labels_left[i][0],explosionX=labels_left[i][6][0]?labels_left[i][6][1]:0,explosionY=labels_left[i][6][0]?labels_left[i][6][2]:0
var ret=RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x+explosionX,y:y+explosionY,text:labels_left[i][2],valign:'center',halign:'right',tag:'labels'});if(ret&&ret.node){ret.node.__index__=labels_left[i][0];}
this.path({path:'lw % b m % % qc % % % % s %',args:[prop.labelsSticksLinewidth,labels_left[i][3][0]+explosionX,labels_left[i][3][1]+explosionY,labels_left[i][4][0]+explosionX,Math.round(labels_left[i][4][1]+explosionY),ret.x+5+ret.width,ret.y+(ret.height/2),labels_left[i][5]]});this.path({path:'b a % % 2 0 6.2830 false, f %',args:[ret.x+5+ret.width,ret.y+(ret.height/2),labels_left[i][5]]});}}};this.drawSticks=function()
{var offset=prop.linewidth/2,exploded=prop.exploded,sticks=prop.labelsSticks,colors=prop.colors,cx=this.centerx,cy=this.centery,radius=this.radius,points=[],linewidth=prop.labelsSticksLinewidth
for(var i=0,len=this.angles.length;i<len;++i){var segment=this.angles[i];if(typeof sticks==='object'&&!sticks[i]){continue;}
var radians=segment[1]-segment[0];this.context.beginPath();this.context.strokeStyle=typeof prop.labelsSticksColors==='string'?prop.labelsSticksColors:(!RGraph.isNull(prop.labelsSticksColors)?prop.labelsSticksColors[i]:'gray');this.context.lineWidth=linewidth;if(typeof prop.labelsSticksColor==='string'){this.context.strokeStyle=prop.labelsSticksColor;}
var midpoint=(segment[0]+(radians/2));if(typeof exploded==='object'&&exploded[i]){var extra=exploded[i];}else if(typeof exploded==='number'){var extra=exploded;}else{var extra=0;}
var stickLength=typeof prop.labelsSticksLength==='object'?prop.labelsSticksLength[i]:prop.labelsSticksLength;points[0]=RGraph.getRadiusEndPoint(cx,cy,midpoint,radius+extra+offset);points[1]=RGraph.getRadiusEndPoint(cx,cy,midpoint,radius+stickLength+extra-5);points[2]=RGraph.getRadiusEndPoint(cx,cy,midpoint,radius+stickLength+extra);points[3]=RGraph.getRadiusEndPoint(cx,cy,midpoint,radius+stickLength+extra);points[3][0]+=(points[3][0]>cx?5:-5);points[4]=[points[2][0]+(points[2][0]>cx?5+prop.labelsSticksHlength:-5-prop.labelsSticksHlength),points[2][1]];this.context.moveTo(points[0][0],points[0][1]);this.context.quadraticCurveTo(points[2][0],points[2][1],points[4][0],points[4][1]);this.context.stroke();this.coordsSticks[i]=[points[0],points[1],points[2],points[3],points[4]];}};this.getShape=function(e)
{var accuracy=arguments[1]?arguments[1]:0;var canvas=this.canvas;var context=this.context;var mouseCoords=RGraph.getMouseXY(e);var mouseX=mouseCoords[0];var mouseY=mouseCoords[1];var r=this.radius;var angles=this.angles;for(var i=0,len=angles.length;i<len;++i){this.context.beginPath();this.context.strokeStyle='rgba(0,0,0,0)';this.context.arc(angles[i][2],angles[i][3],this.radius,angles[i][0],angles[i][1],false);if(this.type=='pie'&&prop.variant=='donut'){this.context.arc(angles[i][2],angles[i][3],(typeof(prop.variantDonutWidth)=='number'?this.radius-prop.variantDonutWidth:this.radius/2),angles[i][1],angles[i][0],true);}else{this.context.lineTo(angles[i][2],angles[i][3]);}
this.context.closePath();if(!this.context.isPointInPath(mouseX,mouseY)){continue;}
if(angles[i][0]<0)angles[i][0]+=RGraph.TWOPI;if(angles[i][1]>RGraph.TWOPI)angles[i][1]-=RGraph.TWOPI;if(RGraph.parseTooltipText&&prop.tooltips){var tooltip=RGraph.parseTooltipText(prop.tooltips,i);}
return{object:this,x:angles[i][2],y:angles[i][3],radius:this.radius,angleStart:angles[i][0],angleEnd:angles[i][1],index:i,dataset:0,sequentialIndex:i,tooltip:typeof tooltip==='string'?tooltip:null};}
return null;};this.drawBorders=function()
{if(prop.linewidth>0){this.context.lineWidth=prop.linewidth;this.context.strokeStyle=prop.colorsStroke;var r=this.radius;for(var i=0,len=this.angles.length;i<len;++i){var segment=this.angles[i];this.context.beginPath();this.context.arc(segment[2],segment[3],r,(segment[0]),(segment[0]+0.001),0);this.context.arc(segment[2],segment[3],prop.variant=='donut'?(typeof(prop.variantDonutWidth)=='number'?this.radius-prop.variantDonutWidth:r/2):r,segment[0],segment[0]+0.0001,0);this.context.closePath();this.context.stroke();}}};this.getRadius=function()
{this.graph={width:this.canvas.width-prop.marginLeft-prop.marginRight,height:this.canvas.height-prop.marginTop-prop.marginBottom};if(typeof(prop.radius)=='number'){this.radius=prop.radius;}else{this.radius=Math.min(this.graph.width,this.graph.height)/2;}
return this.radius;};this.explodeSegment=function(index,size)
{if(typeof this.exploding==='number'&&this.exploding===index){return;}
if(!prop.exploded){prop.exploded=[];}
if(typeof prop.exploded==='number'){var original_explode=prop.exploded;var exploded=prop.exploded;prop.exploded=[];for(var i=0,len=this.data.length;i<len;++i){prop.exploded[i]=exploded;}}
prop.exploded[index]=typeof original_explode=='number'?original_explode:0;this.exploding=index;var delay=RGraph.ISIE&&!RGraph.ISIE10?25:16.666;var obj=this;for(var o=0;o<size;++o){setTimeout(function()
{prop.exploded[index]+=1;RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);},o*delay);}
var obj=this;setTimeout(function()
{obj.exploding=null;},size*delay);};this.highlight_segment=function(segment)
{this.context.beginPath();this.context.strokeStyle=prop.highlightStyleTwodStroke;this.context.fillStyle=prop.highlightStyleTwodFill;this.context.moveTo(segment[0],segment[1]);this.context.arc(segment[0],segment[1],segment[2],this.angles[segment[5]][0],this.angles[segment[5]][1],0);this.context.lineTo(segment[0],segment[1]);this.context.closePath();this.context.stroke();this.context.fill();};this.highlight=function(shape)
{if(prop.tooltipsHighlight){if(typeof prop.highlightStyle==='function'){(prop.highlightStyle)(shape);}else if(prop.highlightStyle=='3d'){this.context.lineWidth=1;var extent=2;this.context.beginPath();RGraph.noShadow(this);this.context.fillStyle='rgba(0,0,0,0)';this.context.arc(shape.x,shape.y,shape.radius,shape.angleStart,shape.angleEnd,false);if(prop.variant=='donut'){this.context.arc(shape.x,shape.y,shape.radius/5,shape.angleEnd,shape.angleStart,true);}else{this.context.lineTo(shape.x,shape.y);}
this.context.closePath();this.context.fill();this.context.beginPath();this.context.shadowColor='#666';this.context.shadowBlur=3;this.context.shadowOffsetX=3;this.context.shadowOffsetY=3;this.context.fillStyle=prop.colors[shape.index];this.context.strokeStyle=prop.colorsStroke;this.context.arc(shape.x-extent,shape.y-extent,shape.radius,shape.angleStart,shape.angleEnd,false);if(prop.variant=='donut'){this.context.arc(shape.x-extent,shape.y-extent,shape.radius/2,shape.angleEnd,shape.angleStart,true)}else{this.context.lineTo(shape.x-extent,shape.y-extent);}
this.context.closePath();this.context.stroke();this.context.fill();RGraph.noShadow(this);if(prop.border){this.context.beginPath();this.context.strokeStyle=prop.borderColor;this.context.lineWidth=5;this.context.arc(shape.x-extent,shape.y-extent,shape.radius-2,shape.angleStart,shape.angleEnd,false);this.context.stroke();}}else if(prop.highlightStyle==='outline'){var tooltip=RGraph.Registry.get('tooltip'),index=tooltip.__index__,coords=this.angles[index],color=this.get('colors')[index]
width=this.radius/12.5;if(typeof prop.highlightStyleOutlineWidth==='number'){width=prop.highlightStyleOutlineWidth;}
this.path('ga 0.25 b a % % % % % false a % % % % % true c f % ga 1',coords[2],coords[3],this.radius+2+width,coords[0],coords[1],coords[2],coords[3],this.radius+2,coords[1],coords[0],color);}else{this.context.beginPath();this.context.strokeStyle=prop.highlightStyleTwodStroke;this.context.fillStyle=prop.highlightStyleTwodFill;if(prop.variant.indexOf('donut')>-1){this.context.arc(shape.x,shape.y,shape.radius,shape.angleStart,shape.angleEnd,false);this.context.arc(shape.x,shape.y,typeof(prop.variantDonutWidth)=='number'?this.radius-prop.variantDonutWidth:shape.radius/2,shape.angleEnd,shape.angleStart,true);}else{this.context.arc(shape.x,shape.y,shape.radius+1,shape.angleStart,shape.angleEnd,false);this.context.lineTo(shape.x,shape.y);}
this.context.closePath();this.context.stroke();this.context.fill();}}};this.getObjectByXY=function(e)
{if(this.getShape(e)){return this;}};this.drawCenterpin=function()
{if(typeof prop.centerpin==='number'&&prop.centerpin>0){var cx=this.centerx;var cy=this.centery;this.context.beginPath();this.context.strokeStyle=prop.centerpinStroke?prop.centerpinStroke:prop.colorsStroke;this.context.fillStyle=prop.centerpinFill?prop.centerpinFill:prop.colorsStroke;this.context.moveTo(cx,cy);this.context.arc(cx,cy,prop.centerpin,0,RGraph.TWOPI,false);this.context.stroke();this.context.fill();}};this.drawInGraphLabels=function()
{var context=this.context;var cx=this.centerx;var cy=this.centery;var radius=prop.labelsIngraphRadius;if(radius<=2&&radius>0){radiusFactor=radius;}else{radiusFactor=0.5;}
if(prop.variant=='donut'){var r=this.radius*(0.5+(radiusFactor*0.5));if(typeof(prop.variantDonutWidth)=='number'){var r=(this.radius-prop.variantDonutWidth)+(prop.variantDonutWidth/2);}}else{var r=this.radius*radiusFactor;}
if(radius>2){r=radius;}
for(var i=0,len=this.angles.length;i<len;++i){if(typeof(prop.exploded)=='object'&&typeof(prop.exploded[i])=='number'){var explosion=prop.exploded[i];}else if(typeof(prop.exploded)=='number'){var explosion=parseInt(prop.exploded);}else{var explosion=0;}
var angleStart=this.angles[i][0];var angleEnd=this.angles[i][1];var angleCenter=((angleEnd-angleStart)/2)+angleStart;var coords=RGraph.getRadiusEndPoint(this.centerx,this.centery,angleCenter,r+(explosion?explosion:0));var x=coords[0];var y=coords[1];var text=prop.labelsIngraphSpecific&&typeof(prop.labelsIngraphSpecific[i])=='string'?prop.labelsIngraphSpecific[i]:RGraph.numberFormat({object:this,number:this.data[i].toFixed(prop.labelsIngraphDecimals),unitspre:prop.labelsIngraphUnitsPre,unitspost:prop.labelsIngraphUnitsPost,point:prop.labelsIngraphPoint,thousand:prop.labelsIngraphThousand});if(text){this.context.beginPath();var textConf=RGraph.getTextConf({object:this,prefix:'labelsIngraph'});RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x,y:y,text:text,valign:'center',halign:'center',bounding:prop.labelsIngraphBounding,boundingFill:prop.labelsIngraphBoundingFill,boundingStroke:prop.labelsIngraphBoundingStroke,tag:'labels.ingraph'});this.context.stroke();}}};this.drawCenterLabel=function(label)
{var textConf=RGraph.getTextConf({object:this,prefix:'labelsCenter'});RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:this.centerx,y:this.centery,halign:'center',valign:'center',text:label,bounding:true,boundingFill:'rgba(255,255,255,0.7)',boundingStroke:'rgba(0,0,0,0)',tag:'labels.center'});};this.getAngle=function(value)
{if(value>this.total){return null;}
var angle=(value/this.total)*RGraph.TWOPI;angle+=prop.origin;return angle;};this.parseColors=function()
{if(this.original_colors.length===0){this.original_colors.colors=RGraph.arrayClone(prop.colors);this.original_colors.keyColors=RGraph.arrayClone(prop.keyColors);this.original_colors.colorsStroke=RGraph.arrayClone(prop.colorsStroke);this.original_colors.highlightStroke=RGraph.arrayClone(prop.highlightStroke);this.original_colors.highlightStyleTwodFill=RGraph.arrayClone(prop.highlightStyleTwodFill);this.original_colors.highlightStyleTwodStroke=RGraph.arrayClone(prop.highlightStyleTwodStroke);this.original_colors.labelsIngraphBoundingFill=RGraph.arrayClone(prop.labelsIngraphBoundingFill);this.original_colors.labelsIngraphColor=RGraph.arrayClone(prop.labelsIngraphColor);}
for(var i=0;i<prop.colors.length;++i){prop.colors[i]=this.parseSingleColorForGradient(prop.colors[i]);}
var keyColors=prop.keyColors;if(keyColors){for(var i=0;i<keyColors.length;++i){keyColors[i]=this.parseSingleColorForGradient(keyColors[i]);}}
prop.colorsStroke=this.parseSingleColorForGradient(prop.colorsStroke);prop.highlightStroke=this.parseSingleColorForGradient(prop.highlightStroke);prop.highlightStyleTwodFill=this.parseSingleColorForGradient(prop.highlightStyleTwodFill);prop.highlightStyleTwodStroke=this.parseSingleColorForGradient(prop.highlightStyleTwodStroke);prop.labelsIngraphBoundingFill=this.parseSingleColorForGradient(prop.labelsIngraphBoundingFill);prop.labelsIngraphColor=this.parseSingleColorForGradient(prop.labelsIngraphColor);};this.reset=function()
{};this.parseSingleColorForGradient=function(color)
{if(!color||typeof(color)!='string'){return color;}
if(color.match(/^gradient\((.*)\)$/i)){if(color.match(/^gradient\(({.*})\)$/i)){return RGraph.parseJSONGradient({object:this,def:RegExp.$1});}
var parts=RegExp.$1.split(':');if(prop.variant=='donut'){var radius_start=typeof(prop.variantDonutWidth)=='number'?this.radius-prop.variantDonutWidth:this.radius/2;}else{var radius_start=0;}
var grad=this.context.createRadialGradient(this.centerx,this.centery,radius_start,this.centerx,this.centery,Math.min(this.canvas.width-prop.marginLeft-prop.marginRight,this.canvas.height-prop.marginTop-prop.marginBottom)/2);var diff=1/(parts.length-1);grad.addColorStop(0,RGraph.trim(parts[0]));for(var j=1;j<parts.length;++j){grad.addColorStop(j*diff,RGraph.trim(parts[j]));}}
return grad?grad:color;};this.interactiveKeyHighlight=function(index)
{if(this.angles&&this.angles[index]){var segment=this.angles[index];var x=segment[2];var y=segment[3];var start=segment[0];var end=segment[1];this.context.strokeStyle=prop.keyInteractiveHighlightChartStroke;this.context.fillStyle=prop.keyInteractiveHighlightChartFill;this.context.lineWidth=2;this.context.lineJoin='bevel';this.context.beginPath();this.context.moveTo(x,y);this.context.arc(x,y,this.radius,start,end,false);this.context.closePath();this.context.fill();this.context.stroke();}};this.on=function(type,func)
{if(type.substr(0,2)!=='on'){type='on'+type;}
if(typeof this[type]!=='function'){this[type]=func;}else{RGraph.addCustomEventListener(this,type,func);}
return this;};this.firstDrawFunc=function()
{};this.draw3d=function()
{var scaleX=1.5,depth=prop.variantThreedDepth,prop_shadow=prop.shadow,prop_labels=prop.labels,prop_labelsSticks=prop.labelsSticks
this.set({labels:[],labelsSticks:false,strokestyle:'rgba(0,0,0,0)'});this.set({variant:this.get('variant').replace(/3d/,'')});this.context.setTransform(scaleX,0,0,1,(this.canvas.width*(scaleX)-this.canvas.width)* -0.5,0);for(var i=depth;i>0;i-=1){this.set({centeryAdjust:i});if(i===parseInt(depth/2)){this.set({labels:prop_labels,labelsSticks:prop_labelsSticks});}
if(i===0){this.set({shadow:prop_shadow});}
this.draw();this.set('shadow',false);if(i<=parseInt(depth/2)){this.set({labels:[],labelsSticks:false});}
if(i>1){if(prop.variant.indexOf('donut')!==-1){for(var j=0;j<this.angles.length;++j){this.path({path:'b a % % % % % false a % % % % % true f rgba(0,0,0,0.15)',args:[this.angles[j][2],this.angles[j][3],this.radius+1,this.angles[j][0],this.angles[j][1]*prop.effectRoundrobinMultiplier,false,this.angles[j][2],this.angles[j][3],this.radius/2,this.angles[j][1]*prop.effectRoundrobinMultiplier,this.angles[j][0],true]});}}else{for(var j=0;j<this.angles.length;++j){this.path({path:'b m % % a % % % % % false c f rgba(0,0,0,0.15)',args:[this.angles[j][2],this.angles[j][3],this.angles[j][2],this.angles[j][3],this.radius+1,this.angles[j][0],this.angles[j][1]*prop.effectRoundrobinMultiplier]});}}}}
this.set({variant:this.get('variant')+'3d',shadow:prop_shadow,labels:prop_labels,labelsSticks:prop_labelsSticks});return this;};this.explode=function()
{var obj=this;var opt=arguments[0]?arguments[0]:{};var callback=arguments[1]?arguments[1]:function(){};var frames=opt.frames?opt.frames:30;var frame=0;var maxExplode=Number(typeof opt.radius==='number'?opt.radius:Math.max(this.canvas.width,this.canvas.height));var currentExplode=Number(obj.get('exploded'))||0;var step=(maxExplode-currentExplode)/frames;this.set('labels',null);var iterator=function()
{obj.set('exploded',currentExplode+(step*frame));RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);if(frame++<frames){RGraph.Effects.updateCanvas(iterator);}else{callback(obj);}}
iterator();return this;};this.grow=function()
{var obj=this;var canvas=obj.canvas;var opt=arguments[0]?arguments[0]:{};var frames=opt.frames||30;var frame=0;var callback=arguments[1]?arguments[1]:function(){};var radius=obj.getRadius();prop.radius=0;var iterator=function()
{obj.set('radius',(frame/frames)*radius);RGraph.redrawCanvas(canvas);if(frame++<frames){RGraph.Effects.updateCanvas(iterator);}else{RGraph.redrawCanvas(obj.canvas);callback(obj);}};iterator();return this;};this.roundRobin=function()
{var obj=this,opt=arguments[0]||{},callback=arguments[1]||function(){},frame=0,frames=opt.frames||30,radius=obj.getRadius(),labels=obj.get('labels')
obj.set('events',false);obj.set('labels',[]);var iterator=function()
{obj.set('effectRoundrobinMultiplier',RGraph.Effects.getEasingMultiplier(frames,frame));RGraph.redrawCanvas(obj.canvas);if(frame<frames){RGraph.Effects.updateCanvas(iterator);frame++;}else{obj.set({events:true,labels:labels});RGraph.redrawCanvas(obj.canvas);callback(obj);}};iterator();return this;};this.implode=function()
{var obj=this,opt=arguments[0]||{},callback=arguments[1]||function(){},frames=opt.frames||30,frame=0,explodedMax=Math.max(this.canvas.width,this.canvas.height),exploded=explodedMax;function iterator()
{exploded=explodedMax-((frame/frames)*explodedMax);obj.set('exploded',exploded);RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);if(frame++<frames){RGraph.Effects.updateCanvas(iterator);}else{RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);callback(obj);}}
iterator();return this;};RGraph.register(this);RGraph.parseObjectStyleConfig(this,conf.options);};RGraph.HorseshoeMeter=function(conf)
{this.draw=function()
{var width=typeof conf.options.width==='number'?conf.options.width:5,fgColor=typeof conf.options.colors==='object'&&typeof conf.options.colors[0]==='string'?conf.options.colors[0]:'black',bgColor=typeof conf.options.colors==='object'&&typeof conf.options.colors[1]==='string'?conf.options.colors[1]:'#ddd';conf.value=Math.max(conf.value,conf.min);conf.value=Math.min(conf.value,conf.max);var obj=new RGraph.Pie({id:conf.id,data:[conf.value-conf.min,conf.max-conf.value],options:{centerx:conf.options.centerx,centery:conf.options.centery,radius:conf.options.radius,marginLeft:conf.options.marginLeft||25,marginRight:conf.options.marginRight||25,marginTop:conf.options.marginTop||25,marginBottom:conf.options.marginBottom||25,shadow:false,variant:'donut',variantDonutWidth:width,colors:[fgColor,'transparent'],colorsStroke:'rgba(0,0,0,0)',contextmenu:conf.options.contextmenu}}).draw();obj.on('beforedraw',function(obj)
{obj.path('b lw % a % % % 0 6.2830 false a % % % 6.2830 0 true f %',width,obj.centerx,obj.centery,obj.radius,obj.centerx,obj.centery,obj.radius-width,bgColor);}).on('draw',function(obj)
{obj.path('b a % % % 0 6.2830 false f % s white',obj.centerx,obj.centery-obj.radius+(width/2),width+5,fgColor);var coords=RGraph.getRadiusEndPoint(obj.centerx,obj.centery,obj.angles[0][1],obj.radius-(width/2));obj.path('b a % % % 0 6.2830 false f % s white',coords[0],coords[1],width+5,fgColor);RGraph.text({object:obj,size:typeof conf.options.textSize==='number'?conf.options.textSize:60,font:typeof conf.options.textFont==='string'?conf.options.textFont:'Arial',color:typeof conf.options.textColor==='string'?conf.options.textColor:'black',bold:typeof conf.options.textBold==='boolean'?conf.options.textBold:false,italic:typeof conf.options.textItalic==='boolean'?conf.options.textItalic:false,text:parseInt(conf.min+(obj.data[0]*obj.get('effectRoundrobinMultiplier')))+'%',x:obj.centerx,y:obj.centery,halign:'center',valign:'center'});});RGraph.clear(obj.canvas);if(conf.roundRobin){obj.roundRobin(conf.options.animationOptions,conf.options.animationCallback);}else{obj.draw();}
return obj;};this.roundRobin=function()
{conf.roundRobin=true;if(arguments[0]){conf.options.animationOptions=arguments[0];}
if(arguments[1]){conf.options.animationCallback=arguments[1];}
this.draw();};};RGraph.ActivityMeter=function(conf)
{this.id=conf.id;this.config=conf.config;this.objects=[];this.options={variantDonutWidth:50,animation:null};for(var i in conf.options){if(typeof i==='string'){this.options[i]=conf.options[i];}}
this.draw=function(obj)
{var activityMeter=this;for(var i=0;i<this.config.length;++i){var pie=new RGraph.Pie({id:activityMeter.id,data:[1],options:{colors:[this.config[i].color],colorsStroke:'rgba(0,0,0,0)',shadow:false,variant:'donut',variantDonutWidth:this.options.variantDonutWidth}}).on('draw',function(obj)
{obj.path('b a % % % % % false a % % % % % true f rgba(0,0,0,0.45)',obj.centerx,obj.centery,obj.radius,0,2*Math.PI,obj.centerx,obj.centery,obj.radius-obj.properties.variantDonutWidth,2*Math.PI,0,);});for(var name in this.options){if(typeof name==='string'&&name!=='labels'){pie.set(name,this.options[name]);}}
if(i>0){pie.set('radius',this.objects[0][0].radius-(this.options.variantDonutWidth*i)-(3*i));}
pie.draw();var pie2=new RGraph.Pie({id:activityMeter.id,data:[this.config[i].value,100-this.config[i].value],options:{index:i,variant:'donut',variantDonutWidth:this.options.variantDonutWidth,colors:[this.config[i].color,'rgba(0,0,0,0)'],colorsStroke:'rgba(0,0,0,0)',shadow:false}}).on('draw',function(obj)
{var halfWidth=obj.get('variantDonutWidth')/2;var context=obj.context,endpoint1=RGraph.getRadiusEndPoint(obj.centerx,obj.centery,RGraph.PI+RGraph.HALFPI,obj.radius);endpoint2=RGraph.getRadiusEndPoint(obj.centerx,obj.centery,obj.angles[0][1],obj.radius-halfWidth);obj.path('b a % % % % % false f %',endpoint1[0],endpoint1[1]+halfWidth,halfWidth,0,RGraph.TWOPI,obj.get('colors')[0]);obj.path('b a % % % % % false f %',endpoint2[0],endpoint2[1],halfWidth,0,RGraph.TWOPI,obj.get('colors')[0]);if(activityMeter.config[obj.index].label){RGraph.text({object:obj,text:activityMeter.config[obj.index].label||'',x:obj.centerx,y:obj.centery-obj.radius+(obj.properties.variantDonutWidth/2),halign:'left',valign:'center',color:activityMeter.options.labelColor||'black',size:activityMeter.options.labelSize||20,font:activityMeter.options.labelFont||'Arial,sans-serif',bold:activityMeter.options.labelBold||false,italic:activityMeter.options.labelItalic||false});}
if(typeof activityMeter.config[obj.index].image==='string'){obj.properties.image=new Image();obj.properties.image.src=activityMeter.config[obj.index].image;obj.properties.image.onload=function()
{var maxWidth=obj.properties.variantDonutWidth*0.75;var imageWidth=obj.properties.image.width;var width=imageWidth>maxWidth?maxWidth:imageWidth;obj.context.drawImage(obj.properties.image,obj.centerx-10,obj.centery-obj.radius+(obj.properties.variantDonutWidth/2)-(width/2),width,width,);};}});for(var name in this.options){if(typeof name==='string'&&name!=='labels'){pie2.set(name,this.options[name]);}}
if(i>0){pie2.set('radius',this.objects[0][0].radius-(this.options.variantDonutWidth*i)-(3*i));}
pie2.index=(function(index){return index;})(i);if(this.options.animationEffect==='roundRobin'){pie2.roundRobin(this.options.animationEffectOptions,this.options.animationEffectCallback);}else{pie2.draw();}
this.objects[i]=[pie,pie2];}
return this;};this.roundRobin=function()
{var args=RGraph.getArgs(arguments,'options,callback');this.options.animationEffect='roundRobin';this.options.animationEffectOptions=args.options;this.options.animationEffectCallback=args.callback;this.draw();return this;};};RGraph.SegmentedMeter=function(conf)
{if(conf.value>conf.max){conf.value=conf.max;}
var value=conf.value/conf.max;this.value=conf.value;conf.data=[value,1-value];var options={backgroundColor:'black',value:true,valuePercentage:true,valueUnitsPre:'',valueUnitsPost:'',valueSize:50,valueBold:null,valueItalic:null,valueFont:null,valueColor:null,variant:'donut',variantDonutWidth:50,colors:['red','white'],colorsStroke:'transparent',shadow:false};for(var i in conf.options){if(typeof i==='string'){options[i]=conf.options[i];}}
for(var i in options){if(typeof i==='string'){conf.options[i]=options[i];}}
this.pie=new RGraph.Pie(conf).on('beforedraw',function(obj)
{RGraph.clear(obj.canvas,obj.properties.backgroundColor);}).on('draw',function(obj)
{var width=5;for(var i=0;i<360;i+=10){obj.path({path:'b a % % % % % false l % % c f %',args:[obj.centerx,obj.centery,obj.radius+2,RGraph.toRadians(i-(width/2)),RGraph.toRadians(i+(width/2)),obj.centerx,obj.centery,conf.options.backgroundColor||'white']});}
if(obj.properties.valuePercentage){var value=Math.round((obj.get('effectRoundrobinMultiplier')*obj.data[0]).toFixed(2)*100);}else{var value=(obj.get('effectRoundrobinMultiplier')*conf.value).toFixed(obj.properties.valueDecimals)}
if(obj.properties.value){RGraph.text({object:obj,x:obj.centerx,y:obj.centery,text:obj.properties.valueUnitsPre+value+obj.properties.valueUnitsPost,font:typeof obj.properties.valueFont==='string'?obj.properties.valueFont:obj.properties.textFont,size:typeof obj.properties.valueSize==='number'?obj.properties.valueSize:obj.properties.textSize,color:typeof obj.properties.valueColor==='string'?obj.properties.valueColor:obj.properties.textColor,bold:typeof obj.properties.valueBold==='boolean'?obj.properties.valueBold:obj.properties.textBold,italic:typeof obj.properties.valueItalic==='boolean'?obj.properties.valueItalic:obj.properties.textItalic,valign:'center',halign:'center'});}});return this.pie;};