
RGraph=window.RGraph||{isrgraph:true,isRGraph:true,rgraph:true};RGraph.Radar=function(conf)
{if(typeof conf.data[0]==='number'||typeof conf.data[0]==='string'){conf.data=[conf.data];}
this.id=conf.id;this.canvas=document.getElementById(conf.id);this.context=this.canvas.getContext?this.canvas.getContext("2d"):null;this.canvas.__object__=this;this.type='radar';this.isRGraph=true;this.isrgraph=true;this.rgraph=true;this.data=[];this.max=0;this.uid=RGraph.createUID();this.canvas.uid=this.canvas.uid?this.canvas.uid:RGraph.createUID();this.colorsParsed=false;this.coords=[];this.coordsText=[];this.original_data=[];this.original_colors=[];this.firstDraw=true;for(var i=0,len=conf.data.length;i<len;++i){for(var j=0;j<conf.data[i].length;++j){if(typeof conf.data[i][j]==='string'){conf.data[i][j]=parseFloat(conf.data[i][j]);}}
this.original_data.push(RGraph.arrayClone(conf.data[i]));this.data.push(RGraph.arrayClone(conf.data[i]));this.max=Math.max(this.max,RGraph.arrayMax(conf.data[i]));}
this.properties={marginLeft:25,marginRight:25,marginTop:25,marginBottom:25,linewidth:1,colorsStroke:'#aaa',colors:['rgba(255,0,0,0.75)','rgba(0,255,255,0.25)','rgba(255,0,0,0.5)','red','green','blue','pink','aqua','brown','orange','grey'],colorsAlpha:null,circle:0,circleFill:'red',circleStroke:'black',labels:[],labelsFont:null,labelsSize:null,labelsColor:null,labelsBold:null,labelsSize:null,labelsOffset:10,labelsAxes:'',labelsBackgroundFill:'white',labelsBoxed:false,labelsAxesFont:null,labelsAxesSize:null,labelsAxesColor:null,labelsAxesBold:null,labelsAxesItalic:null,labelsAxesBoxed:null,labelsAxesBoxedZero:true,labelsAxesBoxedBackground:'rgba(255,255,255,0.7)',labelsAxesSpecific:null,labelsAxesCount:5,backgroundCircles:true,backgroundCirclesCount:null,backgroundCirclesColor:'#ddd',backgroundCirclesPoly:true,backgroundCirclesSpokes:24,textSize:12,textFont:'Arial, Verdana, sans-serif',textColor:'black',textBold:false,textItalic:false,textAccessible:true,textAccessibleOverflow:'visible',textAccessiblePointerevents:false,title:'',titleBackground:null,titleHpos:null,titleVpos:null,titleColor:null,titleBold:null,titleItalic:null,titleSize:null,titleFont:null,titleX:null,titleY:null,titleHalign:null,titleValign:null,linewidth:1,key:null,keyBackground:'white',keyShadow:false,keyShadowColor:'#666',keyShadowBlur:3,keyShadowOffsetx:2,keyShadowOffsety:2,keyPosition:'graph',keyHalign:'right',keyPositionGutterBoxed:false,keyPositionX:null,keyPositionY:null,keyColorShape:'square',keyRounded:true,keyLinewidth:1,keyColors:null,keyInteractive:false,keyInteractiveHighlightChartStroke:'rgba(255,0,0,0.3)',keyInteractiveHighlightLabel:'rgba(255,0,0,0.2)',keyLabelsColor:null,keyLabelsFont:null,keyLabelsSize:null,keyLabelsBold:null,keyLabelsItalic:null,keyLabelsOffsetx:0,keyLabelsOffsety:0,contextmenu:null,annotatable:false,annotateColor:'black',annotateLinewidth:1,tooltips:null,tooltipsEvent:'mousemove',tooltipsEffect:'fade',tooltipsCssClass:'RGraph_tooltip',tooltipsHighlight:true,tooltipsNohideonclear:false,highlightStroke:'gray',highlightFill:'rgba(255,255,255,0.7)',highlightPointRadius:2,resizable:false,resizeHandleAdjust:[0,0],resizeHandleBackground:null,scaleMax:null,scaleDecimals:0,scalePoint:'.',scaleThousand:',',scaleUnitsPre:'',scaleUnitsPost:'',accumulative:false,radius:null,centerx:null,centery:null,radius:null,xaxisTickmarksCount:5,yaxisTickmarksCount:5,axesColor:'rgba(0,0,0,0)',highlights:false,highlightsStroke:'#ddd',highlightsFill:null,highlightsRadius:3,fillClick:null,fillMousemove:null,fillTooltips:null,fillHighlightFill:'rgba(255,255,255,0.7)',fillHighlightStroke:'rgba(0,0,0,0)',fillMousemoveRedraw:false,animationTraceClip:1,clearto:'rgba(0,0,0,0)'}
for(var dataset=0;dataset<this.data.length;++dataset){if(this.data[dataset].length<3){alert('[RADAR] You must specify at least 3 data points');return;}}
var idx=0;for(var dataset=0;dataset<this.data.length;++dataset){for(var i=0,len=this.data[dataset].length;i<len;++i){this['$'+(idx++)]={};}}
if(!this.canvas.__rgraph_aa_translated__){this.context.translate(0.5,0.5);this.canvas.__rgraph_aa_translated__=true;}
var prop=this.properties;this.path=RGraph.pathObjectFunction;if(RGraph.Effects&&typeof RGraph.Effects.decorate==='function'){RGraph.Effects.decorate(this);}
this.responsive=RGraph.responsive;this.set=function(name)
{var value=typeof arguments[1]==='undefined'?null:arguments[1];if(arguments.length===1&&typeof arguments[0]==='object'){for(i in arguments[0]){if(typeof i==='string'){this.set(i,arguments[0][i]);}}
return this;}
prop[name]=value;return this;};this.get=function(name)
{return prop[name];};this.draw=function()
{RGraph.fireCustomEvent(this,'onbeforedraw');this.coords=[];this.coords2=[];this.coordsText=[];this.data=RGraph.arrayClone(this.original_data);if(prop.accumulative){for(var i=0;i<this.data.length;++i){if(this.data[i].length!=this.data[0].length){alert('[RADAR] Error! When the radar has the accumulative option set to true all the datasets must have the same number of elements');}}}
if(RGraph.isNull(prop.labelsAxesBoxed)){prop.labelsAxesBoxed=[];for(var i=0;i<((RGraph.isArray(prop.labelsAxesSpecific)&&prop.labelsAxesSpecific.length)||prop.labelsAxesCount||5);++i){prop.labelsAxesBoxed[i]=false;}}
this.marginLeft=prop.marginLeft;this.marginRight=prop.marginRight;this.marginTop=prop.marginTop;this.marginBottom=prop.marginBottom;this.centerx=((this.canvas.width-this.marginLeft-this.marginRight)/2)+this.marginLeft;this.centery=((this.canvas.height-this.marginTop-this.marginBottom)/2)+this.marginTop;this.radius=Math.min(this.canvas.width-this.marginLeft-this.marginRight,this.canvas.height-this.marginTop-this.marginBottom)/2;if(typeof prop.centerx==='number')this.centerx=2*prop.centerx;if(typeof prop.centery==='number')this.centery=2*prop.centery;if(typeof prop.radius==='number')this.radius=prop.radius;if(!this.colorsParsed){this.parseColors();this.colorsParsed=true;}
if(!prop.scaleMax){if(prop.accumulative){var accumulation=[];var len=this.original_data[0].length
for(var i=1;i<this.original_data.length;++i){if(this.original_data[i].length!=len){alert('[RADAR] Error! Stacked Radar chart datasets must all be the same size!');}
for(var j=0;j<this.original_data[i].length;++j){this.data[i][j]+=this.data[i-1][j];this.max=Math.max(this.max,this.data[i][j]);}}}
this.scale2=RGraph.getScale({object:this,options:{'scale.max':typeof prop.scaleMax==='number'?prop.scaleMax:this.max,'scale.min':0,'scale.decimals':Number(prop.scaleDecimals),'scale.point':prop.scalePoint,'scale.thousand':prop.scaleThousand,'scale.round':prop.scaleRound,'scale.units.pre':prop.scaleUnitsPre,'scale.units.post':prop.scaleUnitsPost,'scale.labels.count':prop.labelsAxesCount}});this.max=this.scale2.max;}else{var ymax=prop.scaleMax;this.scale2=RGraph.getScale({object:this,options:{'scale.max':ymax,'scale.min':0,'scale.strict':true,'scale.decimals':Number(prop.scaleDecimals),'scale.point':prop.scalePoint,'scale.thousand':prop.scaleThousand,'scale.round':prop.scaleRound,'scale.units.pre':prop.scaleUnitsPre,'scale.units.post':prop.scaleUnitsPost,'scale.labels.count':prop.labelsAxesCount}});this.max=this.scale2.max;}
this.drawBackground();this.drawAxes();this.drawCircle();this.drawLabels();this.context.save();this.context.beginPath();this.context.arc(this.centerx,this.centery,this.radius*2,-RGraph.HALFPI,(RGraph.TWOPI*prop.animationTraceClip)-RGraph.HALFPI,false);this.context.lineTo(this.centerx,this.centery);this.context.closePath();this.context.clip();this.drawChart();this.drawHighlights();this.context.restore();this.drawAxisLabels();if(prop.title){RGraph.drawTitle(this,prop.title,this.marginTop,null,null)}
if(prop.key){RGraph.drawKey(this,prop.key,prop.colors);}
if(prop.contextmenu){RGraph.showContext(this);}
if(prop.resizable){RGraph.allowResizing(this);}
RGraph.installEventListeners(this);if((prop.fillClick||prop.fillMousemove||!RGraph.isNull(prop.fillTooltips))&&!this.__fill_click_listeners_installed__){this.addFillListeners();this.__fill_click_listeners_installed__=true;}
if(this.firstDraw){this.firstDraw=false;RGraph.fireCustomEvent(this,'onfirstdraw');this.firstDrawFunc();}
RGraph.fireCustomEvent(this,'ondraw');return this;};this.exec=function(func)
{func(this);return this;};this.drawBackground=function()
{var color=prop.backgroundCirclesColor;var poly=prop.backgroundCirclesPoly;var spacing=prop.backgroundCirclesSpacing;var spokes=prop.backgroundCirclesSpokes;this.context.lineWidth=1;if(prop.backgroundCircles&&poly==false){this.context.strokeStyle=color;this.context.beginPath();var numrings=typeof(prop.backgroundCirclesCount)=='number'?prop.backgroundCirclesCount:prop.labelsAxesCount;for(var r=0;r<=this.radius;r+=(this.radius/numrings)){this.context.moveTo(this.centerx,this.centery);this.context.arc(this.centerx,this.centery,r,0,RGraph.TWOPI,false);}
this.context.stroke();this.context.strokeStyle=color;for(var i=0;i<360;i+=(360/spokes)){this.context.beginPath();this.context.arc(this.centerx,this.centery,this.radius,(i/360)*RGraph.TWOPI,((i+0.001)/360)*RGraph.TWOPI,false);this.context.lineTo(this.centerx,this.centery);this.context.stroke();}}else if(prop.backgroundCircles&&poly==true){this.context.strokeStyle=color;var increment=360/this.data[0].length
for(var i=0;i<360;i+=increment){this.context.beginPath();this.context.arc(this.centerx,this.centery,this.radius,((i/360)*RGraph.TWOPI)-RGraph.HALFPI,(((i+0.001)/360)*RGraph.TWOPI)-RGraph.HALFPI,false);this.context.lineTo(this.centerx,this.centery);this.context.stroke();}
this.context.strokeStyle=color;var numrings=typeof prop.backgroundCirclesCount==='number'?prop.backgroundCirclesCount:prop.labelsAxesCount;for(var r=0;r<=this.radius;r+=(this.radius/numrings)){this.context.beginPath();for(var a=0;a<=360;a+=(360/this.data[0].length)){this.context.arc(this.centerx,this.centery,r,RGraph.toRadians(a)-RGraph.HALFPI,RGraph.toRadians(a)+0.001-RGraph.HALFPI,false);}
this.context.closePath();this.context.stroke();}}};this.drawAxes=function()
{this.context.strokeStyle=prop.axesColor;this.context.lineWidth=prop.axesLinewidth;var halfsize=this.radius;this.context.beginPath();this.context.moveTo(Math.round(this.centerx),this.centery+this.radius);this.context.lineTo(Math.round(this.centerx),this.centery-this.radius);this.context.moveTo(this.centerx-5,Math.round(this.centery+this.radius));this.context.lineTo(this.centerx+5,Math.round(this.centery+this.radius));this.context.moveTo(this.centerx-5,Math.round(this.centery-this.radius));this.context.lineTo(this.centerx+5,Math.round(this.centery-this.radius));for(var y=(this.centery-this.radius);y<(this.centery+this.radius);y+=(this.radius/prop.yaxisTickmarksCount)){this.context.moveTo(this.centerx-3,Math.round(y));this.context.lineTo(this.centerx+3,Math.round(y));}
this.context.moveTo(this.centerx-this.radius,Math.round(this.centery));this.context.lineTo(this.centerx+this.radius,Math.round(this.centery));this.context.moveTo(Math.round(this.centerx-this.radius),this.centery-5);this.context.lineTo(Math.round(this.centerx-this.radius),this.centery+5);this.context.moveTo(Math.round(this.centerx+this.radius),this.centery-5);this.context.lineTo(Math.round(this.centerx+this.radius),this.centery+5);for(var x=(this.centerx-this.radius);x<(this.centerx+this.radius);x+=(this.radius/prop.xaxisTickmarksCount)){this.context.moveTo(Math.round(x),this.centery-3);this.context.lineTo(Math.round(x),this.centery+3);}
this.context.stroke();};this.drawChart=function()
{var alpha=prop.colorsAlpha;if(typeof(alpha)=='number'){var oldAlpha=this.context.globalAlpha;this.context.globalAlpha=alpha;}
var numDatasets=this.data.length;for(var dataset=0;dataset<this.data.length;++dataset){this.context.beginPath();var coords_dataset=[];for(var i=0;i<this.data[dataset].length;++i){var coords=this.getCoordinates(dataset,i);if(coords_dataset==null){coords_dataset=[];}
coords_dataset.push(coords);this.coords.push(coords);}
this.coords2[dataset]=coords_dataset;this.context.strokeStyle=(typeof(prop.colorsStroke)=='object'&&prop.colorsStroke[dataset])?prop.colorsStroke[dataset]:prop.colorsStroke;this.context.fillStyle=prop.colors[dataset]?prop.colors[dataset]:'rgba(0,0,0,0)';if(this.context.fillStyle==='transparent'){this.context.fillStyle='rgba(0,0,0,0)';}
this.context.lineWidth=prop.linewidth;for(i=0;i<coords_dataset.length;++i){if(i==0){this.context.moveTo(coords_dataset[i][0],coords_dataset[i][1]);}else{this.context.lineTo(coords_dataset[i][0],coords_dataset[i][1]);}}
if(prop.accumulative&&dataset>0){this.context.lineTo(coords_dataset[0][0],coords_dataset[0][1]);this.context.moveTo(last_coords[0][0],last_coords[0][1]);for(var i=coords_dataset.length-1;i>=0;--i){this.context.lineTo(last_coords[i][0],last_coords[i][1]);}}
var last_coords=coords_dataset;this.context.closePath();this.context.fill();this.context.stroke();}
if(typeof(alpha)=='number'){this.context.globalAlpha=oldAlpha;}};this.getCoordinates=function(dataset,index)
{var len=this.data[dataset].length;var mag=(this.data[dataset][index]/this.max)*this.radius;var angle=(RGraph.TWOPI/len)*index;angle-=RGraph.HALFPI;var x=Math.cos(angle)*mag;var y=Math.sin(angle)*mag;x=this.centerx+x;y=this.centery+y;return[x,y];};this.drawLabels=function()
{var labels=prop.labels;if(labels&&labels.length>0){this.context.lineWidth=1;this.context.strokeStyle='gray';this.context.fillStyle=prop.labelsColor||prop.textColor;var bgFill=prop.labelsBackgroundFill,bold=prop.labelsBold,bgBoxed=prop.labelsBoxed,offset=prop.labelsOffset,font=prop.textFont,size=prop.textSize,radius=this.radius,color=prop.labelsColor||prop.textColor
for(var i=0;i<labels.length;++i){var angle=(RGraph.TWOPI/prop.labels.length)*i;angle-=RGraph.HALFPI;var x=this.centerx+(Math.cos(angle)*(radius+offset));var y=this.centery+(Math.sin(angle)*(radius+offset));var halign=x<this.centerx?'right':'left';if(i==0||(i/labels.length)==0.5)halign='center';if(labels[i]&&labels[i].length){var textConf=RGraph.getTextConf({object:this,prefix:'labels'});RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x,y:y,text:labels[i],valign:'center',halign:halign,bounding:bgBoxed,boundingFill:bgFill,tag:'labels'});}}}};this.drawCircle=function()
{var circle={};circle.limit=prop.circle;circle.fill=prop.circleFill;circle.stroke=prop.circleStroke;if(circle.limit){var r=(circle.limit/this.max)*this.radius;this.context.fillStyle=circle.fill;this.context.strokeStyle=circle.stroke;this.context.beginPath();this.context.arc(this.centerx,this.centery,r,0,RGraph.TWOPI,0);this.context.fill();this.context.stroke();}};this.drawAxisLabels=function()
{if(RGraph.isArray(prop.labelsAxesSpecific)&&prop.labelsAxesSpecific.length){this.drawSpecificAxisLabels();return;}
this.context.lineWidth=1;this.context.fillStyle='black';this.context.strokeStyle='black';var r=this.radius,font=prop.textFont,axes=prop.labelsAxes.toLowerCase(),color=prop.labelsAxesBoxedBackground,drawzero=false,units_pre=prop.scaleUnitsPre,units_post=prop.scaleUnitsPost,decimals=prop.scaleDecimals,bold=prop.labelsAxesBold,boxed=prop.labelsAxesBoxed,centerx=this.centerx,centery=this.centery,scale=this.scale;this.context.fillStyle=prop.textColor;var textConf=RGraph.getTextConf({object:this,prefix:'labelsAxes'});if(axes.indexOf('n')>-1){for(var i=0;i<this.scale2.labels.length;++i){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:centerx,y:centery-(r*((i+1)/this.scale2.labels.length)),text:this.scale2.labels[i],valign:'center',halign:'center',bounding:boxed[i]||color,boundingFill:color,boundingStroke:'rgba(0,0,0,0)',tag:'scale'});}
drawzero=true;}
if(axes.indexOf('s')>-1){for(var i=0;i<this.scale2.labels.length;++i){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:centerx,y:centery+(r*((i+1)/this.scale2.labels.length)),text:this.scale2.labels[i],valign:'center',halign:'center',bounding:boxed[i]||color,boundingFill:color,boundingStroke:'rgba(0,0,0,0)',tag:'scale'});}
drawzero=true;}
if(axes.indexOf('e')>-1){for(var i=0;i<this.scale2.labels.length;++i){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:centerx+(r*((i+1)/this.scale2.labels.length)),y:centery,text:this.scale2.labels[i],valign:'center',halign:'center',bounding:boxed[i]||color,boundingFill:color,boundingStroke:'rgba(0,0,0,0)',tag:'scale'});}
drawzero=true;}
if(axes.indexOf('w')>-1){for(var i=0;i<this.scale2.labels.length;++i){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:centerx-(r*((i+1)/this.scale2.labels.length)),y:centery,text:this.scale2.labels[i],valign:'center',halign:'center',bounding:boxed[i]||color,boundingFill:color,boundingStroke:'rgba(0,0,0,0)',tag:'scale'});}
drawzero=true;}
if(drawzero){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:centerx,y:centery,text:RGraph.numberFormat({object:this,number:Number(0).toFixed(),unitspre:units_pre,unitspost:units_post}),valign:'center',halign:'center',bounding:color?true:false,boundingFill:color,boundingStroke:'rgba(0,0,0,0)',tag:'scale'});}};this.drawSpecificAxisLabels=function()
{var labels=prop.labelsAxesSpecific;var bold=RGraph.arrayPad(prop.labelsAxesBold,labels.length);var boxed=RGraph.arrayPad(prop.labelsAxesBoxed,labels.length);var reversed_labels=RGraph.arrayReverse(labels);var reversed_bold=RGraph.arrayReverse(bold);var reversed_boxed=RGraph.arrayReverse(boxed);var font=prop.textFont;var axes=prop.labelsAxestextowerCase();this.context.fillStyle=prop.textColor;var textConf=RGraph.getTextConf({object:this,prefix:'labelsAxes'});for(var i=0;i<labels.length;++i){if(axes.indexOf('n')>-1)RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,tag:'labels.axes.specific',x:this.centerx,y:this.centery-this.radius+((this.radius/labels.length)*i),text:reversed_labels[i],valign:'center',halign:'center',bounding:reversed_boxed[i],boundingFill:'white'});if(axes.indexOf('s')>-1)RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,tag:'labels.axes.specific',x:this.centerx,y:this.centery+((this.radius/labels.length)*(i+1)),text:labels[i],valign:'center',halign:'center',bounding:boxed[i],boundingFill:'white'});if(axes.indexOf('w')>-1)RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,tag:'labels.axes.specific',x:this.centerx-this.radius+((this.radius/labels.length)*i),y:this.centery,text:reversed_labels[i],valign:'center',halign:'center',bounding:reversed_boxed[i],boundingFill:'white'});if(axes.indexOf('e')>-1)RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,tag:'labels.axes.specific',x:this.centerx+((this.radius/labels.length)*(i+1)),y:this.centery,text:labels[i],valign:'center',halign:'center',bounding:boxed[i],boundingFill:'white'});}};this.getShape=function(e)
{for(var i=0;i<this.coords.length;++i){var x=this.coords[i][0];var y=this.coords[i][1];var tooltips=prop.tooltips;var index=Number(i);var mouseXY=RGraph.getMouseXY(e);var mouseX=mouseXY[0];var mouseY=mouseXY[1];if(mouseX<(x+5)&&mouseX>(x-5)&&mouseY>(y-5)&&mouseY<(y+5)){if(RGraph.parseTooltipText){var tooltip=RGraph.parseTooltipText(prop.tooltips,index);}
var indexes=RGraph.sequentialIndexToGrouped(index,this.data);var dataset=indexes[0];var idx=indexes[1];return{object:this,x:x,y:y,index:idx,dataset:dataset,sequentialIndex:index,tooltip:typeof tooltip==='string'?tooltip:null}}}};this.highlight=function(shape)
{if(typeof prop.highlightStyle==='function'){(prop.highlightStyle)(shape);}else{RGraph.Highlight.point(this,shape);}};this.getObjectByXY=function(e)
{var mouseXY=RGraph.getMouseXY(e);if(mouseXY[0]>(this.centerx-this.radius)&&mouseXY[0]<(this.centerx+this.radius)&&mouseXY[1]>(this.centery-this.radius)&&mouseXY[1]<(this.centery+this.radius)){return this;}};this.drawHighlights=function()
{if(prop.highlights){var sequentialIdx=0;var dataset=0;var index=0;var radius=prop.highlightsRadius;for(var dataset=0;dataset<this.data.length;++dataset){for(var index=0;index<this.data[dataset].length;++index){this.context.beginPath();this.context.strokeStyle=prop.highlightsStroke;this.context.fillStyle=prop.highlightsFill?prop.highlightsFill:((typeof(prop.colorsStroke)=='object'&&prop.colorsStroke[dataset])?prop.colorsStroke[dataset]:prop.colorsStroke);this.context.arc(this.coords[sequentialIdx][0],this.coords[sequentialIdx][1],radius,0,RGraph.TWOPI,false);this.context.stroke();this.context.fill();++sequentialIdx;}}}};this.getRadius=function(value)
{if(value<0||value>this.max){return null;}
var radius=(value/this.max)*this.radius;return radius;};this.getAngle=function(numitems,index)
{var angle=(RGraph.TWOPI/numitems)*index;angle-=RGraph.HALFPI;return angle;};this.parseColors=function()
{if(this.original_colors.length===0){this.original_colors.colors=RGraph.arrayClone(prop.colors);this.original_colors.keyColors=RGraph.arrayClone(prop.keyColors);this.original_colors.titleColor=RGraph.arrayClone(prop.titleColor);this.original_colors.textColor=RGraph.arrayClone(prop.textColor);this.original_colors.labelsColor=RGraph.arrayClone(prop.labelsColor);this.original_colors.labelsAxesColor=RGraph.arrayClone(prop.labelsAxesColor);this.original_colors.highlightStroke=RGraph.arrayClone(prop.highlightStroke);this.original_colors.highlightFill=RGraph.arrayClone(prop.highlightFill);this.original_colors.circleFill=RGraph.arrayClone(prop.circleFill);this.original_colors.circleStroke=RGraph.arrayClone(prop.circleStroke);this.original_colors.colorsStroke=RGraph.arrayClone(prop.colorsStroke);}
for(var i=0;i<prop.colors.length;++i){prop.colors[i]=this.parseSingleColorForGradient(prop.colors[i]);}
var keyColors=prop.keyColors;if(typeof(keyColors)!='null'&&keyColors&&keyColors.length){for(var i=0;i<prop.keyColors.length;++i){prop.keyColors[i]=this.parseSingleColorForGradient(prop.keyColors[i]);}}
prop.titleColor=this.parseSingleColorForGradient(prop.titleColor);prop.textColor=this.parseSingleColorForGradient(prop.textColor);prop.labelsColor=this.parseSingleColorForGradient(prop.labelsColor);prop.labelsAxesColor=this.parseSingleColorForGradient(prop.labelsAxesColor);prop.highlightStroke=this.parseSingleColorForGradient(prop.highlightStroke);prop.highlightFill=this.parseSingleColorForGradient(prop.highlightFill);prop.circleFill=this.parseSingleColorForGradient(prop.circleFill);prop.circleStroke=this.parseSingleColorForGradient(prop.circleStroke);if(typeof prop.colorsStroke==='object'){for(var i=0;i<prop.colorsStroke.length;++i){prop.colorsStroke[i]=this.parseSingleColorForGradient(prop.colorsStroke[i]);}}else{prop.colorsStroke=this.parseSingleColorForGradient(prop.colorsStroke);}};this.reset=function()
{};this.parseSingleColorForGradient=function(color)
{if(!color||typeof(color)!='string'){return color;}
if(color.match(/^gradient\((.*)\)$/i)){if(color.match(/^gradient\(({.*})\)$/i)){return RGraph.parseJSONGradient({object:this,def:RegExp.$1});}
var parts=RegExp.$1.split(':');var grad=this.context.createRadialGradient(this.centerx,this.centery,0,this.centerx,this.centery,this.radius);var diff=1/(parts.length-1);grad.addColorStop(0,RGraph.trim(parts[0]));for(var j=1;j<parts.length;++j){grad.addColorStop(j*diff,RGraph.trim(parts[j]));}}
return grad?grad:color;};this.addFillListeners=function(e)
{var obj=this;var func=function(e)
{var coords=obj.coords;var coords2=obj.coords2;var mouseXY=RGraph.getMouseXY(e);var dataset=0;if(e.type=='mousemove'&&prop.fillMousemoveRedraw){RGraph.redrawCanvas(obj.canvas);}
for(var dataset=(obj.coords2.length-1);dataset>=0;--dataset){obj.context.beginPath();obj.context.moveTo(obj.coords2[dataset][0][0],obj.coords2[dataset][0][1]);for(var j=0;j<obj.coords2[dataset].length;++j){obj.context.lineTo(obj.coords2[dataset][j][0],obj.coords2[dataset][j][1]);}
obj.context.lineTo(obj.coords2[dataset][0][0],obj.coords2[dataset][0][1]);if(prop.accumulative&&dataset>0){obj.context.lineTo(obj.coords2[dataset-1][0][0],obj.coords2[dataset-1][0][1]);for(var j=(obj.coords2[dataset-1].length-1);j>=0;--j){obj.context.lineTo(obj.coords2[dataset-1][j][0],obj.coords2[dataset-1][j][1]);}}
obj.context.closePath();if(obj.context.isPointInPath(mouseXY[0],mouseXY[1])){var inPath=true;break;}}
if(inPath){var fillTooltips=prop.fillTooltips;if(e.type=='click'){if(prop.fillClick){prop.fillClick(e,dataset);}
if(prop.fillTooltips&&prop.fillTooltips[dataset]){obj.datasetTooltip(e,dataset);}}
if(e.type=='mousemove'){if(prop.fillMousemove){prop.fillMousemove(e,dataset);}
if(!RGraph.isNull(fillTooltips)){e.target.style.cursor='pointer';}
if(prop.fillTooltips&&prop.fillTooltips[dataset]){e.target.style.cursor='pointer';}}
e.stopPropagation();}else if(e.type=='mousemove'){obj.canvas.style.cursor='default';}};if(prop.fillClick||!RGraph.isNull(prop.fillTooltips)){this.canvas.addEventListener('click',func,false);}
if(prop.fillMousemove||!RGraph.isNull(prop.fillTooltips)){this.canvas.addEventListener('mousemove',func,false);}};this.highlightDataset=function(dataset)
{this.context.beginPath();for(var j=0;j<this.coords2[dataset].length;++j){if(j==0){this.context.moveTo(this.coords2[dataset][0][0],this.coords2[dataset][0][1]);}else{this.context.lineTo(this.coords2[dataset][j][0],this.coords2[dataset][j][1]);}}
this.context.lineTo(this.coords2[dataset][0][0],this.coords2[dataset][0][1]);if(prop.accumulative&&dataset>0){this.context.lineTo(this.coords2[dataset-1][0][0],this.coords2[dataset-1][0][1]);for(var j=(this.coords2[dataset-1].length-1);j>=0;--j){this.context.lineTo(this.coords2[dataset-1][j][0],this.coords2[dataset-1][j][1]);}}
this.context.strokeStyle=prop.fillHighlightStroke;this.context.fillStyle=prop.fillHighlightFill;this.context.stroke();this.context.fill();};this.datasetTooltip=function(e,dataset)
{this.highlightDataset(dataset);var text=prop.fillTooltips[dataset];var x=this.coords2[dataset][0][0]+RGraph.getCanvasXY(this.canvas)[0];var y=this.coords2[dataset][0][1]+RGraph.getCanvasXY(this.canvas)[1];RGraph.tooltip({object:this,text:text,x:x,y:y,index:0,event:e});};this.interactiveKeyHighlight=function(index)
{var coords=this.coords2[index];if(coords){var pre_linewidth=this.context.lineWidth;var pre_linecap=this.context.lineCap;this.context.lineWidth=prop.linewidth+10;this.context.lineCap='round';this.context.strokeStyle=prop.keyInteractiveHighlightChartStroke;this.context.beginPath();for(var i=0,len=coords.length;i<len;i+=1){if(i==0){this.context.moveTo(coords[i][0],coords[i][1]);}else{this.context.lineTo(coords[i][0],coords[i][1]);}}
this.context.closePath();this.context.stroke();this.context.lineWidth=pre_linewidth;this.context.lineCap=pre_linecap;}};this.on=function(type,func)
{if(type.substr(0,2)!=='on'){type='on'+type;}
if(typeof this[type]!=='function'){this[type]=func;}else{RGraph.addCustomEventListener(this,type,func);}
return this;};this.firstDrawFunc=function()
{};this.grow=function()
{var obj=this;var callback=arguments[1]?arguments[1]:function(){};var opt=arguments[0]?arguments[0]:{};var frames=opt.frames?opt.frames:30;var frame=0;var data=RGraph.arrayClone(obj.data);function iterator()
{for(var i=0,len=data.length;i<len;++i){for(var j=0,len2=data[i].length;j<len2;++j){obj.original_data[i][j]=(frame/frames)*data[i][j];}}
RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);if(frame<frames){frame++;RGraph.Effects.updateCanvas(iterator);}else{callback(obj);}}
iterator();return this;};this.trace=function()
{var obj=this;var opt=arguments[0]||{};var frames=opt.frames||60;var frame=0;var callback=arguments[1]||function(){};obj.set('animationTraceClip',0);var iterator=function()
{if(frame<frames){obj.set('animationTraceClip',frame/frames);frame++;RGraph.redrawCanvas(obj.canvas);RGraph.Effects.updateCanvas(iterator);}else{obj.set('animationTraceClip',1);RGraph.redrawCanvas(obj.canvas);callback(obj);}};iterator();return this;};RGraph.register(this);RGraph.parseObjectStyleConfig(this,conf.options);};