
RGraph=window.RGraph||{isrgraph:true,isRGraph:true,rgraph:true};RGraph.Gantt=function(conf)
{var id=conf.id
var canvas=document.getElementById(id);var data=conf.data;this.id=id;this.canvas=canvas;this.context=this.canvas.getContext?this.canvas.getContext("2d",{alpha:(typeof id==='object'&&id.alpha===false)?false:true}):null;this.canvas.__object__=this;this.type='gantt';this.isRGraph=true;this.isrgraph=true;this.rgraph=true;this.uid=RGraph.createUID();this.canvas.uid=this.canvas.uid?this.canvas.uid:RGraph.createUID();this.data=data;this.colorsParsed=false;this.coordsText=[];this.original_colors=[];this.firstDraw=true;this.properties={backgroundBarsCount:null,backgroundBarsColor1:'rgba(0,0,0,0)',backgroundBarsColor2:'rgba(0,0,0,0)',backgroundGrid:true,backgroundGridLinewidth:1,backgroundGridColor:'#ddd',backgroundGridHsize:20,backgroundGridVsize:20,backgroundGridHlines:true,backgroundGridVlines:true,backgroundGridBorder:true,backgroundGridAlign:true,backgroundGridAutofit:true,backgroundGridAutofitAlign:true,backgroundGridHlinesCount:null,backgroundGridVlinesCount:null,backgroundVbars:[],backgroundHbars:[],textSize:12,textFont:'Arial, Verdana, sans-serif',textColor:'black',textBold:false,textItalic:false,textAccessible:true,textAccessibleOverflow:'visible',textAccessiblePointerevents:false,marginLeft:75,marginRight:25,marginTop:35,marginBottom:25,marginInner:2,labelsInbar:null,labelsInbarBgcolor:null,labelsInbarAlign:'left',labelsInbarSize:null,labelsInbarFont:null,labelsInbarColor:null,labelsInbarBold:null,labelsInbarItalic:null,labelsInbarAbove:false,labelsComplete:true,labelsCompleteFont:null,labelsCompleteSize:null,labelsCompleteColor:null,labelsCompleteBold:null,labelsCompleteItalic:null,title:'',titleBackground:null,titleX:null,titleY:null,titleBold:null,titleItalic:null,titleFont:null,titleSize:null,titleColor:null,titleHalign:null,titleValign:null,yaxisLabelsFont:null,yaxisLabelsSize:null,yaxisLabelsColor:null,yaxisLabelsBold:null,yaxisLabelsItalic:null,yaxisTitle:'',yaxisTitleBold:null,yaxisTitleItalic:null,yaxisTitleFont:null,yaxisTitleSize:null,yaxisTitleColor:null,yaxisTitlePos:null,yaxisTitlePosition:'right',yaxisTitleX:null,yaxisTitleY:null,xaxisLabels:[],xaxisLabelsFont:null,xaxisLabelsSize:null,xaxisLabelsColor:null,xaxisLabelsBold:null,xaxisLabelsItalic:null,xaxisLabelsAlign:'bottom',xaxisTitle:'',xaxisTitleX:null,xaxisTitleY:null,xaxisTitleBold:null,xaxisTitleColor:null,xaxisTitleFont:null,xaxisTitleSize:null,xaxisTitleItalic:null,xaxisScaleMin:0,xaxisScaleMax:0,colorsDefault:'white',borders:true,coords:[],tooltips:null,tooltipsEffect:'fade',tooltipsCssClass:'RGraph_tooltip',tooltipsHighlight:true,tooltipsEvent:'onclick',highlightStroke:'rgba(0,0,0,0)',highlightFill:'rgba(255,255,255,0.7)',contextmenu:null,annotatable:false,annotatableColor:'black',resizable:false,resizableHandleAdjust:[0,0],resizableHandleBackground:null,adjustable:false,adjustableOnly:null,clearto:'rgba(0,0,0,0)'}
if(!data){alert('[GANTT] The Gantt chart event data is now supplied as the second argument to the constructor - please update your code');}else{for(var i=0,idx=0;i<data.length;++i){if(typeof data[i].start==='string')data[i].start=parseFloat(data[i].start);if(typeof data[i].duration==='string')data[i].duration=parseFloat(data[i].duration);if(typeof data[i].complete==='string')data[i].complete=parseFloat(data[i].complete);if(typeof data[i].linewidth==='string')data[i].linewidth=parseFloat(data[i].linewidth);}}
for(var i=0,idx=0;i<data.length;++i){if(RGraph.isArray(this.data[i])){for(var j=0;j<this.data[i].length;++j){this['$'+(idx++)]={};}}else{this['$'+(idx++)]={};}}
if(!this.canvas.__rgraph_aa_translated__){this.context.translate(0.5,0.5);this.canvas.__rgraph_aa_translated__=true;}
var prop=this.properties;this.path=RGraph.pathObjectFunction;if(RGraph.Effects&&typeof RGraph.Effects.decorate==='function'){RGraph.Effects.decorate(this);}
this.responsive=RGraph.responsive;this.set=function(name)
{var value=typeof arguments[1]==='undefined'?null:arguments[1];if(arguments.length===1&&typeof arguments[0]==='object'){for(i in arguments[0]){if(typeof i==='string'){this.set(i,arguments[0][i]);}}
return this;}
prop[name]=value;return this;};this.get=function(name)
{return prop[name];};this.draw=function()
{RGraph.fireCustomEvent(this,'onbeforedraw');this.marginLeft=prop.marginLeft;this.marginRight=prop.marginRight;this.marginTop=prop.marginTop;this.marginBottom=prop.marginBottom;this.coordsText=[];if(!this.colorsParsed){this.parseColors();this.colorsParsed=true;}
this.graphArea=this.canvas.width-this.marginLeft-this.marginRight;this.graphHeight=this.canvas.height-this.marginTop-this.marginBottom;this.numEvents=this.data.length
this.barHeight=this.graphHeight/this.numEvents;this.halfBarHeight=this.barHeight/2;if(RGraph.isNull(prop.backgroundGridHlinesCount)){this.set('backgroundGridHlinesCount',this.data.length);}
RGraph.Background.draw(this);this.drawLabels();this.drawEvents();if(prop.contextmenu){RGraph.showContext(this);}
if(prop.resizable){RGraph.allowResizing(this);}
RGraph.installEventListeners(this);if(this.firstDraw){this.firstDraw=false;RGraph.fireCustomEvent(this,'onfirstdraw');this.firstDrawFunc();}
RGraph.fireCustomEvent(this,'ondraw');return this;};this.exec=function(func)
{func(this);return this;};this.drawLabels=function()
{var labels=prop.xaxisLabels,labelsColor=prop.xaxisLabelsColor||prop.textColor,labelSpace=(this.graphArea)/labels.length,x=this.marginLeft+(labelSpace/2),y=this.marginTop-(prop.textSize/2)-5,font=prop.textFont,size=prop.textSize;this.context.beginPath();this.context.fillStyle=prop.textColor;this.context.strokeStyle='black'
if(prop.xaxisLabelsAlign=='bottom'){y=this.canvas.height-this.marginBottom+size+2;}
var textConf=RGraph.getTextConf({object:this,prefix:'xaxisLabels'});for(i=0;i<labels.length;++i){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x+(i*labelSpace),y:y,text:String(labels[i]),halign:'center',valign:'center',tag:'labels.horizontal'});}
for(var i=0,len=this.data.length;i<len;++i){var ev=this.data[i],x=this.marginLeft,y=this.marginTop+this.halfBarHeight+(i*this.barHeight);this.context.fillStyle=labelsColor||prop.textColor;var label=RGraph.isArray(ev)?String(ev[0].label||''):String(ev.label||'');var textConf=RGraph.getTextConf({object:this,prefix:'yaxisLabels'});if(label){RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x-5,y:y,text:label,halign:'right',valign:'center',tag:'labels.vertical'});}}};this.drawEvents=function()
{var events=this.data;this.coords=[];if(prop.backgroundVbars){for(i=0,len=prop.backgroundVbars.length;i<len;++i){if(prop.backgroundVbars[i][0]+prop.backgroundVbars[i][1]>prop.xaxisScaleMax){prop.backgroundVbars[i][1]=364-prop.backgroundVbars[i][0];}
var barX=this.marginLeft+(((prop.backgroundVbars[i][0]-prop.xaxisScaleMin)/(prop.xaxisScaleMax-prop.xaxisScaleMin))*this.graphArea),barY=this.marginTop,width=(this.graphArea/(prop.xaxisScaleMax-prop.xaxisScaleMin))*prop.backgroundVbars[i][1],height=this.canvas.height-this.marginTop-this.marginBottom;if((barX+width)>(this.canvas.width-this.marginRight)){width=this.canvas.width-this.marginRight-barX;}
this.context.fillStyle=prop.backgroundVbars[i][2];this.context.fillRect(barX,barY,width,height);}}
if(prop.backgroundHbars){for(i=0,len=prop.backgroundHbars.length;i<len;++i){if(prop.backgroundHbars[i]){var barX=this.marginLeft,barY=((this.canvas.height-this.marginTop-this.marginBottom)/this.data.length)*i+this.marginTop,width=this.graphArea,height=this.barHeight
this.context.fillStyle=prop.backgroundHbars[i];this.context.fillRect(barX,barY,width,height);}}}
var sequentialIndex=0;for(i=0;i<events.length;++i){if(typeof events[i].start==='number'){this.drawSingleEvent(events[i],i,sequentialIndex++);}else{for(var j=0;j<events[i].length;++j){var index=j;this.drawSingleEvent(events[i][j],i,sequentialIndex++,index);}}}};this.getShape=function(e)
{var mouseXY=RGraph.getMouseXY(e),mouseX=mouseXY[0],mouseY=mouseXY[1];for(var i=0,len=this.coords.length;i<len;i++){var left=this.coords[i][0],top=this.coords[i][1],width=this.coords[i][2],height=this.coords[i][3];if(mouseX>=left&&mouseX<=(left+width)&&mouseY>=top&&mouseY<=(top+height)){if(RGraph.parseTooltipText&&prop.tooltips){var tooltip=RGraph.parseTooltipText(prop.tooltips,i);}
var ret={object:this,x:left,y:top,width:width,height:height,dataset:this.coords[i][4].dataset,index:(this.coords[i][4]&&typeof this.coords[i][4].index==='number'?this.coords[i][4].index:0),sequentialIndex:this.coords[i][5],tooltip:typeof tooltip==='string'?tooltip:null};return ret;}}};this.drawSingleEvent=function(ev,dataset,sequentialIndex)
{ev.dataset=dataset;if(typeof arguments[3]==='number'){ev.index=arguments[3]}
var min=prop.xaxisScaleMin;this.context.beginPath();this.context.strokeStyle='black';this.context.fillStyle=ev.color?ev.color:prop.colorsDefault;var barStartX=this.marginLeft+(((ev.start-min)/(prop.xaxisScaleMax-min))*this.graphArea),barStartY=this.marginTop+(dataset*this.barHeight),barWidth=(ev.duration/(prop.xaxisScaleMax-min))*this.graphArea;if((barStartX+barWidth)>(this.canvas.width-this.marginRight)){barWidth=this.canvas.width-this.marginRight-barStartX;}
this.coords.push([barStartX,barStartY+prop.marginInner,barWidth,this.barHeight-(2*prop.marginInner),ev,sequentialIndex,]);if(prop.borders||typeof ev.border==='number'){this.context.strokeStyle=typeof(ev.border)==='string'?ev.border:'black';this.context.lineWidth=(typeof(ev.linewidth)==='number'?ev.linewidth:1);if(ev.linewidth!==0){this.context.strokeRect(barStartX,barStartY+prop.marginInner,barWidth,this.barHeight-(2*prop.marginInner));}}
if(RGraph.isNull(ev.complete)){this.context.fillStyle=ev.color?ev.color:prop.colorsDefault;}else{this.context.fillStyle=ev.background?ev.background:prop.colorsDefault;}
this.context.fillRect(barStartX,barStartY+prop.marginInner,barWidth,this.barHeight-(2*prop.marginInner));var complete=(ev.complete/100)*barWidth;if(typeof(ev.complete)==='number'){this.context.fillStyle=ev.color?ev.color:'#0c0';this.context.fillRect(barStartX,barStartY+prop.marginInner,(ev.complete/100)*barWidth,this.barHeight-(2*prop.marginInner));if(prop.labelsComplete){this.context.beginPath();var textConf=RGraph.getTextConf({object:this,prefix:'labelsComplete'});RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:barStartX+barWidth+5,y:barStartY+this.halfBarHeight,text:String(ev.complete)+'%',valign:'center',tag:'labels.complete'});}}
if(prop.labelsInbar&&prop.labelsInbar[sequentialIndex]){var label=String(prop.labelsInbar[sequentialIndex]),halign=prop.labelsInbarAlign=='left'?'left':'center';halign=prop.labelsInbarAlign=='right'?'right':halign;if(halign=='right'){var x=(barStartX+barWidth)-5;}else if(halign=='center'){var x=barStartX+(barWidth/2);}else{var x=barStartX+5;}
if(prop.labelsInbarAbove){x=barStartX+barWidth+5;halign='left';}
var textConf=RGraph.getTextConf({object:this,prefix:'labelsInbar'});this.context.fillStyle=prop.labelsInbarColor;RGraph.text({object:this,font:textConf.font,size:textConf.size,color:textConf.color,bold:textConf.bold,italic:textConf.italic,x:x,y:barStartY+this.halfBarHeight,text:label,valign:'center',halign:halign,bounding:typeof(prop.labelsInbarBgcolor)=='string',boundingFill:typeof(prop.labelsInbarBgcolor)==='string'?prop.labelsInbarBgcolor:null,tag:'labels.inbar'});}};this.highlight=function(shape)
{if(typeof prop.highlightStyle==='function'){(prop.highlightStyle)(shape);}else{RGraph.Highlight.rect(this,shape);}};this.getObjectByXY=function(e)
{var mouseXY=RGraph.getMouseXY(e);if(mouseXY[0]>this.marginLeft&&mouseXY[0]<(this.canvas.width-this.marginRight)&&mouseXY[1]>this.marginTop&&mouseXY[1]<(this.canvas.height-this.marginBottom)){return this;}};this.adjusting_mousemove=function(e)
{if(prop.adjustable&&RGraph.Registry.get('adjusting')&&RGraph.Registry.get('adjusting').uid==this.uid){var bar=RGraph.Registry.get('adjusting.gantt');if(bar){var mouseXY=RGraph.getMouseXY(e),obj=bar.object,dataset=bar.dataset,index=bar.index,diff=((mouseXY[0]-bar.mousex)/(obj.canvas.width-obj.marginLeft-obj.marginRight))*prop.xaxisScaleMax,eventStart=bar.event_start||0,duration=bar.event_duration,event=typeof obj.data[dataset][index]==='object'?obj.data[dataset][index]:obj.data[dataset]
if(bar['mode']==='move'){diff=Math.round(diff);if(!RGraph.isArray(obj.data[dataset])){event.start=eventStart+diff;if(eventStart+diff<0){obj.data[dataset].start=0;}else if((eventStart+diff+obj.data[dataset].duration)>prop.xaxisScaleMax){obj.data[dataset].start=prop.xaxisScaleMax-obj.data[dataset].duration;}}else{var dataset=bar.dataset,index=typeof bar.index==='number'?bar.index:0,event=obj.data[dataset][index];event.start=eventStart+diff;if((eventStart+diff)<0){event.start=0;}else if((eventStart+diff+event.duration)>prop.xaxisScaleMax){event.start=prop.xaxisScaleMax-event.duration;}}}else if(bar.mode=='resize'){if(mouseXY[0]>(obj.canvas.width-obj.marginRight)){mouseXY[0]=obj.canvas.width-obj.marginRight;}
var diff=((mouseXY[0]-RGraph.Registry.get('adjusting.gantt')['mousex'])/(obj.canvas.width-obj.marginLeft-obj.marginRight))*prop.xaxisScaleMax;diff=Math.round(diff);if(!RGraph.isArray(obj.data[dataset])){obj.data[dataset].duration=duration+diff;if(obj.data[dataset].duration<0){obj.data[dataset].duration=1;}}else{obj.data[dataset][index].duration=duration+diff;if(obj.data[dataset][index].duration<=0){obj.data[dataset][index].duration=1;}}}
RGraph.resetColorsToOriginalValues(obj);RGraph.redrawCanvas(obj.canvas);RGraph.fireCustomEvent(obj,'onadjust');}}};this.getXCoord=function(value)
{var min=prop.xaxisScaleMin,max=prop.xaxisScaleMax,graphArea=this.canvas.width-this.marginLeft-this.marginRight;if(value>max||value<min){return null;}
var x=(((value-min)/(max-min))*graphArea)+this.marginLeft;return x;};this.getValue=function(arg)
{if(arg.length==2){var mouseXY=arg;}else{var mouseXY=RGraph.getMouseXY(arg);}
var mouseX=mouseXY[0],mouseY=mouseXY[1];var value=(mouseX-this.marginLeft)/(this.canvas.width-this.marginLeft-this.marginRight);value*=(prop.xaxisScaleMax-prop.xaxisScaleMin);if(value<prop.xaxisScaleMin||value>prop.xaxisScaleMax){value=null;}
return value;};this.parseColors=function()
{if(this.original_colors.length===0){this.original_colors.data=RGraph.arrayClone(this.data);this.original_colors.backgroundBarsColor1=RGraph.arrayClone(prop.backgroundBarsColor1);this.original_colors.backgroundBarsColor2=RGraph.arrayClone(prop.backgroundBarsColor2);this.original_colors.backgroundGridColor=RGraph.arrayClone(prop.backgroundGridColor);this.original_colors.colorsDefault=RGraph.arrayClone(prop.colorsDefault);this.original_colors.highlightStroke=RGraph.arrayClone(prop.highlightStroke);this.original_colors.highlightFill=RGraph.arrayClone(prop.highlightFill);}
for(var i=0,sequentialIndex=0;i<this.data.length;++i){if(RGraph.isArray(this.data[i])&&typeof this.data[i][0]==='object'&&typeof this.data[i][0].start==='number'){for(var j=0,len=this.data[i].length;j<len;j+=1,sequentialIndex+=1){this.data[i][j].background=this.parseSingleColorForGradient(this.data[i][j].background,{start:this.data[i][j].start,duration:this.data[i][j].duration});this.data[i][j].color=this.parseSingleColorForGradient(this.data[i][j].color,{start:this.data[i][j].start,duration:this.data[i][j].duration});}}else{if(typeof this.data[i].background==='string'){this.data[i].background=this.parseSingleColorForGradient(this.data[i].background,{start:this.data[i].start,duration:this.data[i].duration});}
if(typeof this.data[i].color==='string'){this.data[i].color=this.parseSingleColorForGradient(this.data[i].color,{start:this.data[i].start,duration:this.data[i].duration});}
++sequentialIndex;}}
prop.backgroundBarsColor1=this.parseSingleColorForGradient(prop.backgroundBarsColor1);prop.backgroundBarsColor2=this.parseSingleColorForGradient(prop.backgroundBarsColor2);prop.backgroundGridColor=this.parseSingleColorForGradient(prop.backgroundGridColor);prop.backgroundColor=this.parseSingleColorForGradient(prop.backgroundColor);prop.colorsDefault=this.parseSingleColorForGradient(prop.colorsDefault);prop.highlightStroke=this.parseSingleColorForGradient(prop.highlightStroke);prop.highlightFill=this.parseSingleColorForGradient(prop.highlightFill);};this.reset=function()
{};this.parseSingleColorForGradient=function(color)
{var opts=arguments[1]||{};if(!color||typeof(color)!='string'){return color;}
if(color.match(/^gradient\((.*)\)$/i)){if(color.match(/^gradient\(({.*})\)$/i)){return RGraph.parseJSONGradient({object:this,def:RegExp.$1});}
var parts=RegExp.$1.split(':'),value=(opts.start+opts.duration)>prop.xaxisScaleMax?prop.xaxisScaleMax:(opts.start+opts.duration);var grad=this.context.createLinearGradient(typeof opts.start==='number'?this.getXCoord(opts.start):this.marginLeft,0,typeof opts.start==='number'?this.getXCoord(value):this.canvas.width-this.marginRight,0);var diff=1/(parts.length-1);grad.addColorStop(0,RGraph.trim(parts[0]));for(var j=1;j<parts.length;++j){grad.addColorStop(j*diff,RGraph.trim(parts[j]));}}
return grad?grad:color;};this.on=function(type,func)
{if(type.substr(0,2)!=='on'){type='on'+type;}
if(typeof this[type]!=='function'){this[type]=func;}else{RGraph.addCustomEventListener(this,type,func);}
return this;};this.firstDrawFunc=function()
{};this.grow=function()
{var obj=this,opt=arguments[0]||{},callback=arguments[1]?arguments[1]:function(){},canvas=obj.canvas,context=obj.context,numFrames=opt.frames||30,frame=0;original_events=RGraph.arrayClone(obj.data);function iterator()
{RGraph.clear(obj.canvas);RGraph.redrawCanvas(obj.canvas);if(frame<=numFrames){for(var i=0,len=obj.data.length;i<len;++i){if(typeof obj.data[i]==='object'&&obj.data[i][0]&&typeof obj.data[i][0]==='object'){for(var j=0;j<obj.data[i].length;++j){obj.data[i][j].duration=(frame/numFrames)*original_events[i][j].duration;}}else{obj.data[i].duration=(frame/numFrames)*original_events[i].duration;}}
obj.reset();frame++;RGraph.Effects.updateCanvas(iterator);}else{callback(obj);}}
iterator();return this;};this.resetColorsToOriginalValues=function()
{for(var i=0;i<this.original_colors.data.length;++i){if(this.original_colors.data[i].background){this.data[i].background=RGraph.arrayClone(this.original_colors.data[i].background);}
if(this.original_colors.data[i].color){this.data[i].color=RGraph.arrayClone(this.original_colors.data[i].color);}
if(typeof this.original_colors.data[i][0]==='object'&&typeof this.original_colors.data[i][0].start==='number'){for(var j=0,len2=this.original_colors.data[i].length;j<len2;++j){this.data[i][j].background=RGraph.arrayClone(this.original_colors.data[i][j].background);this.data[i][j].color=RGraph.arrayClone(this.original_colors.data[i][j].color);}}}};this.reset=function()
{this.resetColorsToOriginalValues();this.colorsParsed=false;this.coordsText=[];this.original_colors=[];this.firstDraw=true;this.coords=[];};this.sequentialIndex2Grouped=function(){alert('[RGRAPH] Something went badly wrong - contact support');};this.isAdjustable=function(shape)
{if(RGraph.isNull(prop.adjustableOnly)){return true;}else if(RGraph.isArray(prop.adjustableOnly)&&shape&&prop.adjustableOnly[shape.sequentialIndex]){return true;}
return false;};RGraph.register(this);RGraph.parseObjectStyleConfig(this,conf.options);};